Import('env')

import os

include = env.Install('include/rotatable', ['#include/rotatable.h'])
lib = env.Install('lib', ['../../src/librotatable.a'])

if env["HOST_ARCH"] == env["ARCH"]:
    env.Alias(
        'install',
        env.Install(os.path.join(env['PREFIX'], 'include/rotatable'), include),
    )
    env.Alias('install', env.Install(os.path.join(env['PREFIX'], 'lib'), lib))

env.FSEnvInstallCommonLibConfig()
